name: build API

on:
  push:
    paths:
      - 'records/api.txt'
      - '.github/workflows/main-api.yml'
  workflow_dispatch:

env:
  GitHubMail: "84674445+Zypernia@users.noreply.github.com"
  GitHubName: "Zypernia"

jobs:
  apirunner:
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        name: "Cancel duplicate workflow runs"
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: "Delete old workflow runs"
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: "main-api.yml"
          retain_days: 0
          keep_minimum_runs: 0

      - name: "Set Configs & Secrets for git"
        run: |
          git config --global user.name ${GitHubName}
          git config --global user.email ${GitHubMail}
          git config --global credential.helper store
          echo "https://${{ secrets.GH_TOK }}@github.com" > ~/.git-credentials
      - name: "Setup Python 3"
        uses: actions/setup-python@4.3.0
        with:
          python-version: '3.9.*'

      - name: "Gather api repo"
        continue-on-error: true
        run: |
          git clone "https://${{ secrets.GH_TOK }}@github.com/eyMarv/openfiles-api" api-dev
      - name: "Install dependencies"
        continue-on-error: true
        run: |
          cd api-dev
          parallel ::: 'pip3 install wheel && pip3 install -r requirements.txt' 'bash bootup.sh'
      - name: "Run app builder"
        timeout-minutes: 356
        continue-on-error: true
        run: |
          cd api-dev
          python3 ofxp.py
      - name: "Quality Control"
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY} vwlupo
          cd vwlupo || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > records/api.txt
          git add records/api.txt
          git commit -m "New version of the api | [$(date -u +%D-%T%P)]"
          git push -q "https://${{ secrets.GH_TOK }}@github.com/${GITHUB_REPOSITORY}" -f HEAD:main || exit 1
